
url:
  "https://toplinkbot.com/"
cert_file:
  "./cert/toplinkbot_com.crt"
key_file:
  "./cert/toplinkbot_com.pem"
database_url:
  "postgresql://postgres:@localhost:5432/postgres"
redis_url:
  "redis://localhost:6379/0"
mysql:
  address: 127.0.0.1:3306
  database: testdb
  user_name: root
  passwd: root123

debug: true
