
url:
  "https://toplinkbot.com/"
cert_file:
  "./cert/toplinkbot_com.crt"
key_file:
  "./cert/toplinkbot_com.pem"
database_url:
  "postgresql://postgres:@localhost:5432/postgres"
redis_url:
  "redis://localhost:6379/0"


server:
  host: 127.0.0.1
  port: 8081
datasource:
  driverName: mysql
  host: 127.0.0.1
  port: 3306
  database: managerdb
  username: manager
  password: manager
  charset: utf8mb4
  loc: Local
debug: true
